[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd server && npm install", "cd ../client && npm install"]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "cd server && node server.js"